### ISSUE TITLE
project dose not set up a "cJSON.h" file

### ISSUE THREAD

**Issue by wolfgangwayland7** [Jamm02/esp32-audio-router#10]
In file included from /home/wolf/esp/esp-idf/components/json/cJSON/cJSON_Utils.c:53:
/home/wolf/esp/esp-idf/components/json/cJSON/cJSON_Utils.h:31:10: fatal error: cJSON.h: No such file or directory
   31 | #include "cJSON.h"
      |          ^~~~~~~~~

**Comment by Jamm02** [comment]
cjson.h resides in the components folder of esp/espidf, confirm this once, if it resides somewhere else you can edit the cmakelist file accordingly.
